/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diet;


import java.awt.Color;


/**
 *
 * @author tmichaud
 */
public class PoidsIdeal extends javax.swing.JFrame {

    private String nom;
    private String prenom;
    private double imc;
    private double poids;
    private double taille;
    double poidsIdeal = 0;
    private int age;
    final private double imcs[] = {16.5, 18.5, 25, 30, 35, 40};
    final private String corpulences[] = {"Famine", "Maigreur",
    "Normale", "Surpoids", "Obésité modérée", "Obésité sévère", "Obésité","morbide"};
    final private int NBIMC = 6;
    final private int NBCORPULENCE = 7;
    
    public PoidsIdeal() {
        initComponents();
        
        getContentPane().setBackground(new java.awt.Color(204, 255, 204));
        
        jPanelPoidsIdeal.setVisible(false);
       
        jPanelInformations.setBackground(Color.LIGHT_GRAY);
        jPanelSexe.setBackground(Color.LIGHT_GRAY);
        jPanelPoidsIdeal.setBackground(Color.LIGHT_GRAY);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelInformations = new javax.swing.JPanel();
        jLabelNom = new javax.swing.JLabel();
        jLabelPrenom = new javax.swing.JLabel();
        jLabelSexe = new javax.swing.JLabel();
        jLabelAge = new javax.swing.JLabel();
        jLabelPoids = new javax.swing.JLabel();
        jLabelTaille = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jPanelSexe = new javax.swing.JPanel();
        jRadioHomme = new javax.swing.JRadioButton();
        jRadioFemme = new javax.swing.JRadioButton();
        jSpinnerAge = new javax.swing.JSpinner();
        jSpinnerPoids = new javax.swing.JSpinner();
        jSpinnerTaille = new javax.swing.JSpinner();
        jPanelPoidsIdeal = new javax.swing.JPanel();
        jButtonDevine = new javax.swing.JButton();
        jButtonLorentz = new javax.swing.JButton();
        jButtonLorentzAge = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAfficheur = new javax.swing.JTextArea();
        jButtonSuite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(530, 620));
        setResizable(false);
        setSize(new java.awt.Dimension(530, 620));
        getContentPane().setLayout(null);

        jPanelInformations.setLayout(null);

        jLabelNom.setText("Nom");
        jPanelInformations.add(jLabelNom);
        jLabelNom.setBounds(121, 12, 62, 24);

        jLabelPrenom.setText("Prénom");
        jPanelInformations.add(jLabelPrenom);
        jLabelPrenom.setBounds(121, 42, 62, 24);

        jLabelSexe.setText("Sexe");
        jPanelInformations.add(jLabelSexe);
        jLabelSexe.setBounds(121, 72, 62, 15);

        jLabelAge.setText("Age");
        jPanelInformations.add(jLabelAge);
        jLabelAge.setBounds(121, 101, 47, 23);

        jLabelPoids.setText("Poids");
        jPanelInformations.add(jLabelPoids);
        jLabelPoids.setBounds(121, 130, 62, 23);

        jLabelTaille.setText("Taille");
        jPanelInformations.add(jLabelTaille);
        jLabelTaille.setBounds(121, 159, 62, 24);
        jPanelInformations.add(jTextFieldNom);
        jTextFieldNom.setBounds(195, 15, 172, 21);

        jTextFieldPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrenomActionPerformed(evt);
            }
        });
        jPanelInformations.add(jTextFieldPrenom);
        jTextFieldPrenom.setBounds(195, 45, 172, 21);

        buttonGroup1.add(jRadioHomme);
        jRadioHomme.setText("Homme");
        jRadioHomme.setToolTipText("");

        buttonGroup1.add(jRadioFemme);
        jRadioFemme.setText("Femme");
        jRadioFemme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioFemmeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSexeLayout = new javax.swing.GroupLayout(jPanelSexe);
        jPanelSexe.setLayout(jPanelSexeLayout);
        jPanelSexeLayout.setHorizontalGroup(
            jPanelSexeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSexeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioFemme)
                .addGap(10, 10, 10)
                .addComponent(jRadioHomme, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelSexeLayout.setVerticalGroup(
            jPanelSexeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSexeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelSexeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioHomme)
                    .addComponent(jRadioFemme)))
        );

        jPanelInformations.add(jPanelSexe);
        jPanelSexe.setBounds(195, 72, 182, 23);

        jSpinnerAge.setModel(new javax.swing.SpinnerNumberModel(1, 1, 200, 1));
        jSpinnerAge.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelInformations.add(jSpinnerAge);
        jSpinnerAge.setBounds(195, 103, 173, 20);

        jSpinnerPoids.setModel(new javax.swing.SpinnerNumberModel(15.0d, 15.0d, 300.0d, 0.1d));
        jPanelInformations.add(jSpinnerPoids);
        jSpinnerPoids.setBounds(195, 132, 173, 20);

        jSpinnerTaille.setModel(new javax.swing.SpinnerNumberModel(0.5d, 0.5d, 3.0d, 0.01d));
        jPanelInformations.add(jSpinnerTaille);
        jSpinnerTaille.setBounds(195, 162, 173, 20);

        getContentPane().add(jPanelInformations);
        jPanelInformations.setBounds(10, 10, 370, 190);

        jPanelPoidsIdeal.setLayout(null);

        jButtonDevine.setText("Poids idéal devine");
        jButtonDevine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDevineMouseClicked(evt);
            }
        });
        jPanelPoidsIdeal.add(jButtonDevine);
        jButtonDevine.setBounds(52, 12, 167, 25);

        jButtonLorentz.setText("Poids idéal lorentz");
        jButtonLorentz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLorentzMouseClicked(evt);
            }
        });
        jPanelPoidsIdeal.add(jButtonLorentz);
        jButtonLorentz.setBounds(52, 43, 167, 25);

        jButtonLorentzAge.setText("Poids idéal lorentz / age");
        jButtonLorentzAge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLorentzAgeMouseClicked(evt);
            }
        });
        jPanelPoidsIdeal.add(jButtonLorentzAge);
        jButtonLorentzAge.setBounds(52, 74, 195, 25);

        jTextAreaAfficheur.setColumns(20);
        jTextAreaAfficheur.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAfficheur);

        jPanelPoidsIdeal.add(jScrollPane1);
        jScrollPane1.setBounds(12, 105, 486, 203);

        getContentPane().add(jPanelPoidsIdeal);
        jPanelPoidsIdeal.setBounds(10, 270, 510, 320);

        jButtonSuite.setText("Suite");
        jButtonSuite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSuiteMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonSuite);
        jButtonSuite.setBounds(200, 230, 71, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioFemmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioFemmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioFemmeActionPerformed

    private void jTextFieldPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrenomActionPerformed

    private void jButtonSuiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSuiteMouseClicked
                
    if(jPanelInformations.isVisible())
        {
            jPanelInformations.setVisible(false);
            jPanelPoidsIdeal.setVisible(true);
        }
        else
        {
            jPanelInformations.setVisible(true);
            jPanelPoidsIdeal.setVisible(false);
        }
        
        
        poids = (double) jSpinnerPoids.getValue();
        taille = (double) jSpinnerTaille.getValue();
        age = (int) jSpinnerAge.getValue();
        nom = jTextFieldNom.getText();
        prenom = jTextFieldPrenom.getText();
        jTextAreaAfficheur.append("\nBonjour " + prenom + " " + nom);
        
        imc = (poids/(taille*taille)) ;
        
        jTextAreaAfficheur.append("\nVotre indice de masse corporel est de: " + imc);
        
// recherche de la corpulence de l'individu en fonction de son imc
        int indiceCorpulence = 0;
    for (int i = 0; i < NBIMC - 1; i++) {
        if (imc > imcs[i] && imc <= imcs[i + 1]) {
            indiceCorpulence = i + 1;
        }
    }
// cas extreme
    if (imc < 16.5) {
        indiceCorpulence = 0;
    }
    if (imc > 40) {
        indiceCorpulence = NBCORPULENCE - 1;
    }
        jTextAreaAfficheur.append("\nVotre corpulence est qualifiée de " +corpulences[indiceCorpulence]);
        
        
        
    }//GEN-LAST:event_jButtonSuiteMouseClicked

    private void jButtonDevineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDevineMouseClicked
        
                    
        

if (jRadioFemme.isSelected()) {
    poidsIdeal = (45.5 + 2.3 *(taille / 0.0254 - 60.0));
}

if (jRadioHomme.isSelected()) {
    poidsIdeal = (50.0 + 2.3 *(taille / 0.0254 - 60.0));
}

if (poidsIdeal > 0) {
   jTextAreaAfficheur.append("\nVotre poids ideal avec la formule de devine : " + ((Double) poidsIdeal).toString() + " kg\n");

   double ecart = poids - poidsIdeal;

   if (ecart >= 0) {
            jTextAreaAfficheur.append("\nVous   devez   perdre   "   + ((Double) ecart).toString() + " kg\n");
   } 

   else {
            jTextAreaAfficheur.append("\nVous   devez   prendre   "   + ((Double) (-ecart)).toString() + " kg\n");   

   }
}
        
    }//GEN-LAST:event_jButtonDevineMouseClicked

    private void jButtonLorentzMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLorentzMouseClicked
        
    if (jRadioFemme.isSelected()) {
        poidsIdeal = (taille * 100 - 100 -(taille*100-150)/2.5);
}

    if (jRadioHomme.isSelected()) {
        poidsIdeal = (taille * 100 - 100 -(taille*100-150)/4);
}

    if (poidsIdeal > 0) {
        jTextAreaAfficheur.append("\nVotre poids ideal avec la formule de Lorentz : " + ((Double) poidsIdeal).toString() + " kg\n");

   double ecart = poids - poidsIdeal;

   if (ecart >= 0) {
        jTextAreaAfficheur.append("\nVous   devez   perdre   "   + ((Double) ecart).toString() + " kg\n");
   } 

   else {
        jTextAreaAfficheur.append("\nVous   devez   prendre   "   + ((Double) (-ecart)).toString() + " kg\n");   

   }
    }  
    }//GEN-LAST:event_jButtonLorentzMouseClicked

    private void jButtonLorentzAgeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLorentzAgeMouseClicked
          
        poidsIdeal = 50 + (taille*100-150)/4 +(age-20)/4 ;

    if (poidsIdeal > 0) {
        jTextAreaAfficheur.append("\nVotre poids ideal avec la formule de Lorentz selon l'age mais pas le sexe : " 
                + ((Double) poidsIdeal).toString() + " kg\n");

   double ecart = poids - poidsIdeal;

   if (ecart >= 0) {
        jTextAreaAfficheur.append("\nVous   devez   perdre   "   + ((Double) ecart).toString() + " kg\n");
   } 

   else {
        jTextAreaAfficheur.append("\nVous   devez   prendre   "   + ((Double) (-ecart)).toString() + " kg\n");   

   }
    }  
        
        
    }//GEN-LAST:event_jButtonLorentzAgeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PoidsIdeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PoidsIdeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PoidsIdeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PoidsIdeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PoidsIdeal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonDevine;
    private javax.swing.JButton jButtonLorentz;
    private javax.swing.JButton jButtonLorentzAge;
    private javax.swing.JButton jButtonSuite;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPoids;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JLabel jLabelSexe;
    private javax.swing.JLabel jLabelTaille;
    private javax.swing.JPanel jPanelInformations;
    private javax.swing.JPanel jPanelPoidsIdeal;
    private javax.swing.JPanel jPanelSexe;
    private javax.swing.JRadioButton jRadioFemme;
    private javax.swing.JRadioButton jRadioHomme;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerAge;
    private javax.swing.JSpinner jSpinnerPoids;
    private javax.swing.JSpinner jSpinnerTaille;
    private javax.swing.JTextArea jTextAreaAfficheur;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenom;
    // End of variables declaration//GEN-END:variables
}
